# Generated by Django 3.0.7 on 2020-06-16 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('location', models.CharField(max_length=75, null=True)),
                ('address', models.CharField(max_length=75, null=True)),
                ('website', models.CharField(max_length=75, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=55)),
                ('image_path', models.CharField(max_length=250)),
                ('is_owner', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='businesss', to='capstoneapp.Business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capstoneapp.Customer')),
            ],
            options={
                'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('created_at'), nulls_last=True),),
            },
        ),
        migrations.CreateModel(
            name='RecommendedBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneapp.Business')),
                ('recommended_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_user', to='capstoneapp.Customer')),
                ('recommending_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to='capstoneapp.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='businesss', to='capstoneapp.BusinessType'),
        ),
        migrations.AddField(
            model_name='business',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='capstoneapp.Customer'),
        ),
    ]
