# Generated by Django 3.0.7 on 2020-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0003_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.IntegerField(),
        ),
    ]
