# Generated by Django 3.0.7 on 2020-06-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0004_auto_20200617_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
