# Generated by Django 3.0.7 on 2020-06-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0007_auto_20200619_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.AlterField(
            model_name='review',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesss', to='capstoneapp.Business'),
        ),
    ]
