# Generated by Django 3.0.7 on 2020-06-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0007_auto_20200619_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image_path',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
