# Generated by Django 3.0.7 on 2020-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0008_auto_20200626_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.AddField(
            model_name='customer',
            name='image_path',
            field=models.CharField(default='img', max_length=250),
            preserve_default=False,
        ),
    ]
