# Generated by Django 3.0.7 on 2020-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0009_auto_20200626_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image_path',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
