# Generated by Django 3.0.7 on 2020-06-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0010_auto_20200626_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image_path',
            new_name='image',
        ),
    ]
