# Generated by Django 3.0.7 on 2020-06-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0011_auto_20200626_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.RemoveField(
            model_name='business',
            name='price',
        ),
    ]
