# Generated by Django 3.0.7 on 2020-06-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0012_auto_20200626_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
