# Generated by Django 3.0.7 on 2020-06-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapp', '0013_remove_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
